version: '1'
services:
  spellchecker-service:
    ports:
      - "31337:31337"
    image: spellchecker-service
  spellchecker:
    ports:
      - "5000:5000"
    environment:
      SPELLCHECKER_API: http://localhost:31337/api
    image: spellchecker
    depends_on:
      - spellchecker-service